<!DOCTYPE html>
<html>

<head>
     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
	 <script src="file.js"></script>
</head>
<body>


<iframe  style="position: absolute; margin: 1; padding: 0; top: 0; left: 0; width: 100%; height: 100%;" src="https://playerv.logicahost.com.br/video/cidadetropical/3/false/false/Wkcxc2ExcFhPSGRPVXpWellqSmtjRmt5Um05aU0wNHdURzFPZG1KVE5XbGpaejA5KzM?autoplay=1" width="100%" height="100%" frameborder="0" scrolling="auto" allowfullscreen="allowfullscreen"></iframe>

	
 <div> <video data-dashjs-player autoplay src="../radio/cidade.mp4" controls></video> </div> 

</body>
</html>

